#!/bin/bash

option1=$1
imageName = silvionetto/fotografobrasileiroemamsterdam
imageVersion = 0.0.1

if [ $option1 = "build" ]
then
  docker build -t $imageName:$imageVersion .
elif [ $option1 = "run" ]
then
  winpty docker run -it --cap-add=NET_ADMIN --rm --name ubuntu $imageName:$imageVersion
else
  echo "Invalid Option!"
fi
